### ISSUE TITLE
Contact with the repository owner )

### ISSUE THREAD

**Issue by DarvinHarutyunyan** [zhaorui20005/zhaorui_self_practice#9]
Hi @zhaorui20005, I did not find you on other platforms(linkedin, discord...), and I have no other contacts except GitHub. How can I contact with you without GitHub tricks?

**Comment by zhaorui20005** [comment]
Hi, @DarvinHarutyunyan . My wechat ID is beatifulrui, and 295181573@qq.com is my personal email.
I do not use other platforms because of the GFW.
